### ISSUE TITLE
Investigate error thrown during editing Handlebars-injected string literals

### ISSUE THREAD

**Issue by picimako** [picimako/wiremocha#17]
There is an error thrown by the IntelliJ Platform when editing string literals injected with the Handlebars language.

```
java.lang.AssertionError: Before patch: doc:
'{{#\"aJson\": \"string\"}}'
---PSI:
'{{#\"aJson\": \"string\"}}'
---chars:
'{{#"aJson": "string"}}'.
OK let's see. Host file: PsiJavaFile:WireMochaDemo.java in 'D:\Git\...\WireMochaDemo.java' (Language: JAVA)  (uncommitted)
Was injected Language: Handlebars at ranges: [Shred in PsiLiteralExpression:"{{#\"aJson\": \"string\"}}" with range (496,524) (class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl) inside range (1,27)]
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.parseFile(InjectionRegistrarImpl.java:693)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.reparse(InjectionRegistrarImpl.java:613)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.reparse(InjectedLanguageUtil.java:333)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.reparseChangedInjectedFragments(PsiDocumentManagerImpl.java:175)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:273)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:136)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitAsynchronously$0(DocumentCommitThread.java:79)
```

It is most probably related to the `\` escaping character, because it is thrown when the string contains that.

**Comment by picimako** [comment]
This occurs via the IDE's own language injection functionality as well and has no connection to how the language injection in this plugin is implemented.
While IJ 2021.3 reports this error on the UI as well, 2022.1 hides it, and this error can be seen only in idea.log.
